# Change prefix to C-a
unbind-key C-b              # free the original bind-key key
set-option -g prefix C-a    # setting the prefix from C-b to C-a
bind-key C-a send-prefix    # ensure that we can send Ctrl-A to other apps or the shell that your interacting


# Set vim mode ON TODO: Check keybindings
set-window-option -g mode-keys vi

# Source tmux file
bind r source-file ~/.tmux.conf \; display-message "tmux.conf reloaded"

# swap-window/move-window depending on if target exists
bind-key m command-prompt -p "Move to window number:" \
  "run-shell 'if tmux list-windows -F \"##I\" | grep -qx \"%1\"; then tmux swap-window -t %1; else tmux move-window -t %1; fi && tmux select-window -t %1'"

# Swapping windows
bind-key P swap-window -t -1 \;  previous-window
bind-key N swap-window -t +1 \; next-window


# Window indexing at 1
set-option -g base-index 1                # window index will start with 1
set-window-option -g pane-base-index 1    # pane index will start with 1
set-option -g renumber-windows on         

# Splitting panes
bind-key | split-window -h -c "#{pane_current_path}" # let's open pane with current directory with -c option
bind-key _ split-window -v -c "#{pane_current_path}"

# Killing panes and sessions
unbind-key x               # unbind-key “x” from it’s current job of “ask and then close”
bind-key x kill-pane       # rebind-key it to just “close”
bind-key X kill-session    # key combo for killing the entire session - <prefix> + shift + x

# List of plugins
set -g @plugin 'sainnhe/tmux-fzf'
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'

# Initialize TMUX plugin manager (keep this line at the very bottom of tmux.conf)
run '~/.tmux/plugins/tpm/tpm'
