# Enable Powerlevel10k instant prompt. Should stay close to the top of ~/.zshrc.
# Initialization code that may require console input (password prompts, [y/n]
# confirmations, etc.) must go above this block; everything else may go below.
if [[ -r "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh" ]]; then
  source "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh"
fi

alias ll='ls -alF'
alias nvim="$HOME/bin/nvim-macos-arm64-v0.11.5/bin/nvim"

# kitty
# bindkey "\e[1;3D" backward-word # ⌥←
# bindkey "\e[1;3C" forward-word # ⌥→

# bindkey '^[[1;9D' backward-word
# bindkey '^[[1;9C' forward-word
# Option + Left Arrow → backward word
# bindkey '^[[1;9D' backward-word
# Command + Right Arrow → forward word
# bindkey '^[[1;9C' forward-word



. "$HOME/.local/bin/env"

# Load fzf autocomplete
source <(fzf --zsh)

# Load nvm
export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion

# Add go to PATH
export PATH=$(go env GOPATH)/bin:$PATH

# Configuration for p10k prompt
# To customize prompt, run `p10k configure` or edit ~/.p10k.zsh.
source /opt/homebrew/share/powerlevel10k/powerlevel10k.zsh-theme
[[ ! -f ~/.p10k.zsh ]] || source ~/.p10k.zsh
source /opt/homebrew/share/powerlevel10k/powerlevel10k.zsh-theme
