---
- name: Set package lists
  ansible.builtin.set_fact:
    common_packages:
      - git
      - tmux
      - tmuxinator
      - fzf
      - python3
      - ripgrep
    os_packages: "{{ ['go', 'node'] if ansible_facts.system == 'Darwin' else ['golang', 'nodejs', 'npm'] }}"

- name: Show compiled package list
  ansible.builtin.debug:
    msg: "Installing the following packages: {{ common_packages + os_packages }} | for {{ ansible_facts.system }}"

- name: Run generic package installer
  ansible.builtin.import_tasks: install-package.yaml
  vars:
    packages: "{{ common_packages + os_packages }}"
