- name: Set package list
  ansible.builtin.set_fact:
    common_packages:
      - git
      - tmux
      - tmuxinator
      - fzf
      - python3
      - ripgrep
    os_packages: "{{ ['go', 'node'] if ansible_system == 'Darwin' else ['golang', 'nodejs', 'npm'] }}"

- name: Install packages on macOS via homebrew
  community.general.homebrew:
    name: "{{ common_packages + os_packages }}"
  when: ansible_system == "Darwin"

- name: Install Git and Tmux on Linux via APT
  become: true
  ansible.builtin.apt:
    name: "{{ common_packages + os_packages }}"
    update_cache: true
  when: ansible_system == "Linux"
