---
- name: Configure machines
  hosts: all
  gather_facts: true

  tasks:
    - name: Run system package tasks
      ansible.builtin.import_tasks: tasks/packages.yaml
      tags: packages

    - name: Run dotdrop
      ansible.builtin.import_tasks: tasks/dotdrop.yaml
      tags: dotfiles

    - name: Run Neovim installation tasks
      ansible.builtin.import_tasks: tasks/neovim.yaml
      tags: neovim
